blueprint:
  name: Multi-Sensor Door/Window Alert
  description: Send notifications to mobile devices when any door or window sensor is opened.
  domain: automation
  input:
    door_window_sensors:
      name: Door/Window Sensors
      description: List of door and window sensors to monitor.
      selector:
        entity:
          domain: binary_sensor
          multiple: true
    notify_device:
      name: Notification Devices
      description: Device to receive notifications.
      selector:
        target:
          device:
            integration: mobile_app

trigger:
  platform: state
  entity_id: !input 'door_window_sensors'
  from: 'closed'
  to: 'open'

action:
  - service: notify.notify
    target: !input 'notify_device'
    data:
      message: >
        "{{ state_attr(trigger.to_state.entity_id, 'friendly_name') }} has been opened!"

mode: parallel
max: 10
